### ISSUE TITLE
Please release a new version to NPM

### ISSUE THREAD

**Issue by Titozzz** [KrazyLabs/react-native-app-settings#12]
Hello, would it be possible to get a new version onto NPM ? Would be great 🎉

**Comment by m-vdb** [comment]
need!

**Comment by Titozzz** [comment]
I guess the repo is dead

**Comment by n1ru4l** [comment]
@nmartin867 @seantimm Is it possible to either 

1. Add additional maintainers
2. Transfer this project to react-native-community

**Comment by nmartin867** [comment]
@Titozzz @n1ru4l Sorry for the radio silence. Thanks for hanging in there. I've moved onto a new gig and lost access to this repo temporarily. I will be reviewing PRs and publishing a new version of this module to NPM this evening.

I'm also interested in creating a roadmap for this project. Please let me know if you have ideas.

**Comment by nmartin867** [comment]
@Titozzz @n1ru4l version 2.0.1 has been published to NPM.

**Comment by n1ru4l** [comment]
There is a version 2.0.1 published but no changelog nor the version of the in repo package.json updated.
