### ISSUE TITLE
Let user choose custom settings to open

### ISSUE THREAD

**Issue by renanpupin** [KrazyLabs/react-native-app-settings#2]
One idea of making the library more customizable is to allow the user to pass the custom settings tab that he wishes to open by parameter.

For example:

- open the general settings
OpenAppSettings.open("settings")

- open notification settings
OpenAppSettings.open("notifications")

- open the storage settings
OpenAppSettings.open("storage")

**Comment by nmartin867** [comment]
@renanpupin I am going to try and get this in within the next couple days. Thanks!

**Comment by nmartin867** [comment]
Unfortunately it appears that this is just not possible on IOS.  Lame. :/

https://forums.developer.apple.com/message/186656#186656

**Comment by EmperorEarth** [comment]
Any way to do this on android?

On iOS it can default to current behavior.
